# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from binarytree import Node
final = []
i = 0
treeNode = None
proposition = {}
clause=[]
fnctree = None
shortTree = None
clauses_to_delete =[]

def eleminate_implication(node):
    newnode = Node(node.value)
    if (node.value!='→' and node.value!='↔'and node.value!='¬' and node.value!='∨' and node.value!='∧') :
        # eleminate_implication(node.right)
        # eleminate_implication(node.left)
        return node
    elif(node.value =='→'):
        newnode.value = '∨'
        newnode.left = Node('¬')
        newnode.left.right = eleminate_implication(node.left)
        newnode.right = eleminate_implication(node.right)
    elif(node.value=='↔'):
        newnode.value ='∧'
        newnode.left = Node('∨')
        newnode.left.left = Node('¬')
        newnode.left.left.right = eleminate_implication(node.left)
        newnode.left.right = eleminate_implication(node.right)
        newnode.right = Node('∨')
        newnode.right.left = Node('¬')
        newnode.right.left.right = eleminate_implication(node.right)
        newnode.right.right = eleminate_implication(node.left)
    elif(node.value=='∧'):
        newnode.value = '∧'
        newnode.left = eleminate_implication(node.left)
        newnode.right = eleminate_implication(node.right) 
    elif(node.value=='∨'):
        newnode.value = '∨'
        newnode.left = eleminate_implication(node.left)
        newnode.right = eleminate_implication(node.right) 
    elif(node.value=='¬'):
        newnode.value = '¬'
        newnode.right = eleminate_implication(node.right) 
    return newnode
def eleminate_negation(node):
    newnode = Node(node.value)
    if (node.value!='¬'  and node.value!='∨' and node.value!='∧') :
        # eleminate_negation(newnode.right)
        # eleminate_negation(newnode.left)
        return node
    elif(node.value =='¬'):
        if(node.right.value=='∧'):
            newnode.value = '∨'
            newnode.left = Node('¬')
            newnode.left.right = eleminate_negation(node.right.left)
            newnode.right = Node('¬')
            newnode.right.right = eleminate_negation(node.right.right)
        elif(node.right.value=='∨'):
            newnode.value = '∧'
            newnode.left = Node('¬')
            newnode.left.right = eleminate_negation(node.right.left)
            newnode.right = Node('¬')
            newnode.right.right = eleminate_negation(node.right.right)
        elif(node.right.value=='¬'):
            newnode = node.right.right
        else:
            newnode.right = eleminate_negation(node.right)
    elif(node.value=='∧'):
        newnode.value = '∧'
        newnode.left = eleminate_negation(node.left)
        newnode.right = eleminate_negation(node.right) 
    elif(node.value=='∨'):
        newnode.value = '∨'
        newnode.left = eleminate_negation(node.left)
        newnode.right = eleminate_negation(node.right) 
    return newnode
def verify_negation(node):
    if(node.value=='¬' and (node.right.value == '∧' or node.right.value=='∨'or node.right.value=='¬')):
        return False
    elif(node.value=='¬'):
        return verify_negation(node.right)
    elif(node.value == '∧' or node.value=='∨'):
        if(not (node.left==None) and (node.left.value== '∨' or node.left.value== '∧' or node.left.value== '¬' )):
            if( verify_negation(node.left) == False):
                return False
        if(not (node.right==None) and (node.right.value== '∨' or node.right.value== '∧'or node.right.value== '¬' )):
            if( verify_negation(node.right)==False):
                return False
    return True

def fnc(node):
    newnode = Node(node.value)
    if (node.value!='¬'  and node.value!='∨' and node.value!='∧') :
        return node
    elif(node.value =='∨'):
        if(node.right.value=='∧'):
            if(node.left.value=='∧'):
                newnode.value = '∧'
                newnode.left = Node('∧')
                newnode.left.left = Node('∨')
                newnode.left.left.left = fnc(node.left.left)
                newnode.left.left.right = fnc(node.right.left)
                
                newnode.left.right = Node('∨')
                newnode.left.right.left = fnc(node.left.right)
                newnode.left.right.right = fnc(node.right.left)
                
                newnode.right =  Node('∧')
                newnode.right.left = Node('∨')
                newnode.right.left.left = fnc(node.left.left)
                newnode.right.left.right = fnc(node.right.right)
                newnode.right.right = Node('∨')
                newnode.right.right.left = fnc(node.left.right)
                newnode.right.right.right = fnc(node.right.right)
                
            elif(node.left.value=='∨'):
                newnode.value = '∨'
                newnode.left = fnc(node.left.left)
                newnode.right = Node('∧')
                newnode.right.left = Node('∨')
                newnode.right.left.left = fnc(node.left.right)
                newnode.right.left.right = fnc(node.right.left)
                newnode.right.right = Node('∨')
                newnode.right.right.left = fnc(node.left.right)
                newnode.right.right.right = fnc(node.right.right)
            
            else:
                newnode.value = '∧'
                newnode.left = Node('∨')
                newnode.left.left = fnc(node.left)
                newnode.left.right = fnc(node.right.left)
                newnode.right = Node('∨')
                newnode.right.left = fnc(node.left)
                newnode.right.right = fnc(node.right.right)
        elif(node.left.value=='∧'):
            if(node.right.value=='∨'):
                newnode.value = '∨'
                newnode.left = Node('∧')
                newnode.left.left = Node('∨')
                newnode.left.left.left = fnc(node.left.left)
                newnode.left.left.right = fnc(node.right.left)
                newnode.left.right = Node('∨')
                newnode.left.right.left = fnc(node.left.right)
                newnode.left.right.right = fnc(node.right.left)
                newnode.right = fnc(node.right.right)
            else:
                newnode.value = '∧'
                newnode.left = Node('∨')
                newnode.left.left = fnc(node.left.left)
                newnode.left.right = fnc(node.right)
                newnode.right = Node('∨')
                newnode.right.left = fnc(node.left.right)
                newnode.right.right = fnc(node.right)
        else:
            newnode.value = '∨'
            newnode.left = fnc(node.left)
            newnode.right = fnc(node.right)         
    elif(node.value=='∧'):
        newnode.value = '∧'
        newnode.left = fnc(node.left)
        newnode.right = fnc(node.right) 
    elif(node.value=='¬'):
        newnode.value = '¬' 
        newnode.right = fnc(node.right) 
    return newnode
def verify_fnc(node):
    if(node.value=='∨' and (node.left.value=="∧" or node.right.value=="∧")):
        return False
    else:
        if(not (node.right == None) and (node.right.value == '∨'or node.right.value == '∧')):
            
            if(verify_fnc(node.right) == False):
                return False
                
        if(not (node.left == None) and (node.left.value == '∨'or node.left.value == '∧')):
            if(verify_fnc(node.left)==False):
                return False
    return True

def seperate_clauses(node):
    global i
    # new_conjunction = Node(node.value)
    if node is None:
        return None

    if node.value == '∧':
        # Eliminate opposites and repetitions for both sides of the conjunction
        node.left  = seperate_clauses(node.left)
        node.right  = seperate_clauses(node.right)
    elif node.value == '∨':
        # Eliminate opposites and repetitions within the disjunction
        clause.append([])
        node = eliminate_opposites_and_repetitions_within_disjunction(node)
        i = i+1
    elif node.value == '¬':
        c = []
        c.append('¬')
        c.append(node.right.value)
        clause.append(c)
    else :
        c = []
        c.append(node.value)
        clause.append(c)
    return node 

def eliminate_opposites_and_repetitions_within_disjunction(node):
    # Collect literals and eliminate opposites and repetitions
    global i
    global clause
    new_disjunction = Node('∨')
    if(node.left.value == '∨'):
        new_left = eliminate_opposites_and_repetitions_within_disjunction(node.left)
        if (new_left == None):
            return None
        else:
            new_disjunction.left = new_left
    elif node.left.value == '¬' and node.left.right.value in clause[i]:
        index = clause[i].index(node.left.right.value)
        ##if ~p already exists we delete it
        if clause[index-1]=='¬':
            new_disjunction.left = None
        #if p and ~p the node is deleted
        else:
            clause.pop(i)
            i=i-1
            return None
        #if ~p does not exist already we add it to clauses and new node
    elif node.left.value == '¬' and node.left.right.value not in clause[i]:
        new_disjunction.left = Node('¬')
        new_disjunction.left.right = Node(node.left.right.value)

        #if we have just p and it already exists we delete it
    elif node.left.value  in clause[i]:
        index = clause[i].index(node.left.value)
        if clause[i][index-1]=='¬':
            clause.pop(i)
            i=i-1
            return None
        else:
            new_disjunction.left = None

        # if we haven't seen p in our clause yet we add it to clause and new node

    elif node.left.value not in clause[i]:
            # Not a repetition, add to literals and the new disjunction
        clause[i].append(node.left.value)
        new_disjunction.left = Node(node.left.value)
            #new_disjunction = new_disjunction.right

#the same for right Node
    if(node.right.value == '∨'):
        new_right  = eliminate_opposites_and_repetitions_within_disjunction(node.right)
        if (new_right == None):
            return None
        else:
            new_disjunction.right = new_right
    elif node.right.value == '¬' and node.right.right.value in clause[i]:
        index = clause[i].index(node.right.right.value)
        if clause[i][index-1]=='¬':
            new_disjunction.right = None
        else:
            clause.pop(i)
            i=i-1
            return None
    elif node.right.value == '¬' and node.right.right.value not in clause[i]:
        clause[i].append('¬')
        clause[i].append(node.right.right.value)
        new_disjunction.right = Node('¬')
        new_disjunction.right.right = Node(node.right.right.value)

    elif node.right.value  in clause[i]:
        index = clause[i].index(node.right.value)
        if clause[i][index-1]=='¬':
            clause.pop(i)
            i=i-1
            return None
        else:
            new_disjunction.right = None
    elif node.right.value not in clause[i]:
        clause[i].append(node.right.value)
        new_disjunction.right = Node(node.right.value)
            

    return new_disjunction 

def verify_repetiion_Clause():
    for i in range(0,len(clause)):
        for j in range(0,len(clause)):
            if(j!= i):
                if all(elem in clause[j] for elem in clause[i]):
                    print(clause[j])
                    clauses_to_delete.append(j)

def delete_clauses(node):
    global i
    global clauses_to_delete
    b = int(i)
    if node != None and node.value == '∧':
        # Eliminate opposites and repetitions for both sides of the conjunction
        node.left  = delete_clauses(node.left)
        node.right  = delete_clauses(node.right)
    
    else :
        # Eliminate opposites and repetitions within the disjunction
        if(node!=None):
            if i in clauses_to_delete:
                node = None
            i = i+1
    return node 

def shortened(node):
    if node.value=='∨' or node.value=='∧' :
        if node.right == None or node.left == None:
            return False
        else:
            if(shortened(node.left) == False):
                return False
            if(shortened(node.right) == False):
                return False
            
    return True

def shorten(node):
    newnode = Node(node.value)
    if(node.value == '∨' or node.value == '∧'):
        if(node.left == None and node.right == None):
            return None
        
        if(node.left == None):
            newnode.value = node.right.value
            if(node.right.right!=None):
                newnode.right = shorten(node.right.right)
            if(node.right.left!=None):
                newnode.left = shorten(node.right.left)
        elif(node.right == None):
            newnode.value = node.left.value
            if(node.left.right!=None):
                newnode.right = shorten(node.left.right)
            if(node.left.left!=None):
                newnode.left = shorten(node.left.left)
        else:
            if(node.right!=None):
                newnode.right = shorten(node.right)
            if(node.left!=None):
                newnode.left = shorten(node.left)
    elif(node.value=='¬'):
        newnode.right = Node(node.right.value)
    return newnode
class Ui_TRUEorFALSE(object):
    def setupUi(self, TRUEorFALSE):
        TRUEorFALSE.setObjectName("TRUEorFALSE")
        TRUEorFALSE.resize(558, 545)
        TRUEorFALSE.setStyleSheet("background-color: rgb(255, 242, 216);")
        
        self.centralwidget = QtWidgets.QWidget(TRUEorFALSE)
        self.centralwidget.setObjectName("centralwidget")
        self.enterButton = QtWidgets.QPushButton(self.centralwidget, clicked =lambda: self.enterIt())
        self.enterButton.setGeometry(QtCore.QRect(450, 100, 91, 31))
        self.enterButton.setStyleSheet("background-color: rgb(188, 163, 127);")
        self.enterButton.setObjectName("enterButton")
        self.formule = QtWidgets.QLineEdit(self.centralwidget)
        self.formule.setGeometry(QtCore.QRect(30, 90, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.formule.setFont(font)
        self.formule.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.formule.setText("")
        self.formule.setObjectName("formule")
        self.andB = QtWidgets.QPushButton(self.centralwidget,clicked =lambda: self.press_it("∧"))
        self.andB.setGeometry(QtCore.QRect(130, 140, 40, 30))
        self.andB.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.andB.setObjectName("andB")
        #self.andB.clicked.connect(self.setFocusToLineEdit)
        self.fnc = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.fncB())
        self.fnc.setGeometry(QtCore.QRect(34, 450, 81, 23))
        self.fnc.setStyleSheet("background-color: rgb(188, 163, 127);")
        self.fnc.setObjectName("fnc")
        self.tree = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.treeB())
        self.tree.setGeometry(QtCore.QRect(34, 480, 81, 23))
        self.tree.setStyleSheet("background-color: rgb(188, 163, 127);")
        self.tree.setObjectName("tree")
        self.simpl = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.simplB())
        self.simpl.setGeometry(QtCore.QRect(34, 420, 81, 23))
        self.simpl.setStyleSheet("background-color: rgb(188, 163, 127);")
        self.simpl.setObjectName("simpl")
        self.notB = QtWidgets.QPushButton(self.centralwidget,clicked =lambda: self.press_it("¬"))
        self.notB.setGeometry(QtCore.QRect(30, 140, 40, 30))
        self.notB.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.notB.setObjectName("notB")
        self.orB = QtWidgets.QPushButton(self.centralwidget,clicked =lambda: self.press_it("∨"))
        self.orB.setGeometry(QtCore.QRect(80, 140, 40, 30))
        self.orB.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.orB.setObjectName("orB")
        self.implication = QtWidgets.QPushButton(self.centralwidget,clicked =lambda: self.press_it("→"))
        self.implication.setGeometry(QtCore.QRect(180, 140, 40, 30))
        self.implication.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.implication.setObjectName("implication")
        self.equality = QtWidgets.QPushButton(self.centralwidget,clicked =lambda: self.press_it("↔"))
        self.equality.setGeometry(QtCore.QRect(230, 140, 40, 30))
        self.equality.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.equality.setObjectName("equality")
        self.parClose = QtWidgets.QPushButton(self.centralwidget,clicked =lambda: self.press_it(")"))
        self.parClose.setGeometry(QtCore.QRect(330, 140, 40, 30))
        self.parClose.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.parClose.setObjectName("parClose")
        self.parOpen = QtWidgets.QPushButton(self.centralwidget,clicked =lambda: self.press_it("("))
        self.parOpen.setGeometry(QtCore.QRect(280, 140, 40, 30))
        self.parOpen.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.parOpen.setObjectName("parOpen")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(150, 220, 381, 41))
        self.outputlabel.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.outputlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputlabel.setText("")
        self.outputlabel.setObjectName("outputlabel")
        
        self.backbut = QtWidgets.QPushButton(self.centralwidget ,clicked =lambda: self.backspace())
        self.backbut.setGeometry(QtCore.QRect(380, 140, 91, 31))
        self.backbut.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.backbut.setObjectName("backbut")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(17, 57, 70);")
        self.label_2.setObjectName("label_2")
        self.ClearingB = QtWidgets.QPushButton(self.centralwidget ,clicked =lambda: self.Clearit())
        self.ClearingB.setGeometry(QtCore.QRect(470, 480, 75, 23))
        self.ClearingB.setStyleSheet("background-color: rgb(188, 163, 127);")
        self.ClearingB.setObjectName("ClearingB")
        self.ResultB = QtWidgets.QPushButton(self.centralwidget ,clicked =lambda: self.calculate())
        self.ResultB.setGeometry(QtCore.QRect(370, 390, 75, 23))
        self.ResultB.setStyleSheet("background-color: rgb(188, 163, 127);")
        self.ResultB.setObjectName("ResultB")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 290, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: rgb(17, 57, 70);")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(28)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(17, 57, 70);")
        self.label.setObjectName("label")
        self.ValuesT = QtWidgets.QTableWidget(self.centralwidget)
        self.ValuesT.setGeometry(QtCore.QRect(160, 290, 203, 171))
        self.ValuesT.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.ValuesT.setObjectName("ValuesT")
        self.ValuesT.setColumnCount(2)
        self.ValuesT.setRowCount(0)
        self.tfresult= QtWidgets.QLabel(self.centralwidget)
        self.tfresult.setGeometry(QtCore.QRect(370, 420, 75, 23))
        self.tfresult.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.tfresult.setFrameShape(QtWidgets.QFrame.Box)
        self.tfresult.setText("......")
        self.tfresult.setObjectName("tfresult")
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.tfresult.setAlignment(QtCore.Qt.AlignCenter)
        self.tfresult.setFont(font)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ValuesT.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ValuesT.setHorizontalHeaderItem(1, item)
        TRUEorFALSE.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TRUEorFALSE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 21))
        self.menubar.setObjectName("menubar")
        TRUEorFALSE.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TRUEorFALSE)
        self.statusbar.setObjectName("statusbar")
        TRUEorFALSE.setStatusBar(self.statusbar)

        self.retranslateUi(TRUEorFALSE)
        QtCore.QMetaObject.connectSlotsByName(TRUEorFALSE)

    def retranslateUi(self, TRUEorFALSE):
        _translate = QtCore.QCoreApplication.translate
        TRUEorFALSE.setWindowTitle(_translate("TRUEorFALSE", "MainWindow"))
        self.enterButton.setText(_translate("TRUEorFALSE", "Enter"))
        self.andB.setText(_translate("TRUEorFALSE", "∧"))
        self.tree.setText(_translate("TRUEorFALSE", "Tree"))
        self.fnc.setText(_translate("TRUEorFALSE", "FNC"))
        self.simpl.setText(_translate("TRUEorFALSE", "simplifier"))
        self.notB.setText(_translate("TRUEorFALSE", "¬"))
        self.orB.setText(_translate("TRUEorFALSE", "∨"))
        self.implication.setText(_translate("TRUEorFALSE", "→ "))
        self.equality.setText(_translate("TRUEorFALSE", "↔"))
        self.parClose.setText(_translate("TRUEorFALSE", ")"))
        self.parOpen.setText(_translate("TRUEorFALSE", "("))
        self.backbut.setText(_translate("TRUEorFALSE", "Backspace"))
        self.label_2.setText(_translate("TRUEorFALSE", " Forme postfixee :"))
        self.ClearingB.setText(_translate("TRUEorFALSE", "Clear"))
        self.ResultB.setText(_translate("TRUEorFALSE", "Get Result"))
        #self.ClearingB.setText(_translate("TRUEorFALSE", "Clear"))
        self.label_3.setText(_translate("TRUEorFALSE", "Interpretation :"))
        self.label.setText(_translate("TRUEorFALSE", "Propositional Formula Processor"))
        item = self.ValuesT.horizontalHeaderItem(0)
        item.setText(_translate("TRUEorFALSE", "Proposition"))
        item = self.ValuesT.horizontalHeaderItem(1)
        item.setText(_translate("TRUEorFALSE", "Value"))
        #self.tfresult.setText(_translate("TRUEorFALSE", " ... "))
#### put my functions
    #for buttons that sais and or...
    def press_it(self,pressed):
        newT = self.formule.text()+ pressed
        self.formule.setText (newT)
    def Clearit(self):
        self.formule.setText ('')
        self.outputlabel.setText('')
        self.ValuesT.clearContents()
        self.tfresult.setText('')
        global final
        global treeNode
        global proposition
        final = []
        treeNode = None
        proposition = {}
    #delete last letter
    

    def backspace(self):
        newT = self.formule.text()[:-1]
        self.formule.setText(newT)
    '''def setFocusToLineEdit(self):
        self.formule.setFocus()'''

    #function that draws and shows the tree

    def treeB(self):
        def plot_tree(node, x, y, ax, parent_x=None, parent_y=None):
            if node is not None:
                if parent_x is not None and parent_y is not None:
                    # Draw a line from the parent node to the current node
                    ax.plot([parent_x, x], [parent_y, y], 'b-')
                # Draw the current node
                s = str(node.value)
                if(s=="¬" or s=="∨" or s== "→"or s== "↔" or s=="∧"):
                    c = '#CD6688'
                else :
                    c = '#AED8CC'
                ax.text(x, y, str(node.value), color='000000', ha='center', va='center',
                bbox=dict(facecolor=c, edgecolor='black', boxstyle='circle'))
        # Calculate new coordinates for the child nodes
                dx = 1.0  # Horizontal spacing between nodes
                dy = -1.0  # Vertical spacing between nodes
                next_x = x - dx
                next_y = y + dy
        # Recursively plot the left and right subtrees
                plot_tree(node.left, next_x, next_y, ax, x, y)
                plot_tree(node.right, next_x + dx + dx, next_y, ax, x, y)
                # Create a plot and display the binary tree
        plt.figure(figsize=(8, 6))
        ax = plt.gca()
        global treeNode
        plot_tree(treeNode, 0, 0, ax)
        plt.axis('off')  # Turn off axis labels
        plt.show()

    '''this function algorithme de construction and creates the tree'''
    def fncB(self):
        global fnctree
        global treeNode
        fnctree = (eleminate_implication(treeNode))    
        while(not verify_negation(fnctree)):
            fnctree = eleminate_negation(fnctree)    
        while(not verify_fnc(fnctree)):
            fnctree = fnc(fnctree)
        def plot_tree(node, x, y, ax, parent_x=None, parent_y=None):
            if node is not None:
                if parent_x is not None and parent_y is not None:
                    # Draw a line from the parent node to the current node
                    ax.plot([parent_x, x], [parent_y, y], 'b-')
                # Draw the current node
                s = str(node.value)
                if(s=="¬" or s=="∨" or s== "→"or s== "↔" or s=="∧"):
                    c = '#CD6688'
                else :
                    c = '#AED8CC'
                ax.text(x, y, str(node.value), color='000000', ha='center', va='center',
                bbox=dict(facecolor=c, edgecolor='black', boxstyle='circle'))
        # Calculate new coordinates for the child nodes
                dx = 1.0  # Horizontal spacing between nodes
                dy = -1.0  # Vertical spacing between nodes
                next_x = x - dx
                next_y = y + dy
        # Recursively plot the left and right subtrees
                plot_tree(node.left, next_x, next_y, ax, x, y)
                plot_tree(node.right, next_x + dx + dx, next_y, ax, x, y)
                # Create a plot and display the binary tree
        plt.figure(figsize=(8, 6))
        ax = plt.gca()
        plot_tree(fnctree, 0, 0, ax)
        plt.axis('off')  # Turn off axis labels
        plt.show()

    def simplB(self):
        global i
        i = 0
        shortTree = seperate_clauses(fnctree)
        for s in range(0,len(clause)):
            j= 0
            length = len(clause[s])
            while(j<length):
                if(clause[s][j] == '¬'):
                    clause[s][j] = clause[s][j]+clause[s][j+1]
                    clause[s].pop(j+1)
                    length = length-1
                j=j+1
        verify_repetiion_Clause()
        delete_clauses(shortTree)
        while (not shortened(shortTree)):
            w = shorten(shortTree)
        def plot_tree(node, x, y, ax, parent_x=None, parent_y=None):
            if node is not None:
                if parent_x is not None and parent_y is not None:
                    # Draw a line from the parent node to the current node
                    ax.plot([parent_x, x], [parent_y, y], 'b-')
                # Draw the current node
                s = str(node.value)
                if(s=="¬" or s=="∨" or s== "→"or s== "↔" or s=="∧"):
                    c = '#CD6688'
                else :
                    c = '#AED8CC'
                ax.text(x, y, str(node.value), color='000000', ha='center', va='center',
                bbox=dict(facecolor=c, edgecolor='black', boxstyle='circle'))
        # Calculate new coordinates for the child nodes
                dx = 1.0  # Horizontal spacing between nodes
                dy = -1.0  # Vertical spacing between nodes
                next_x = x - dx
                next_y = y + dy
        # Recursively plot the left and right subtrees
                plot_tree(node.left, next_x, next_y, ax, x, y)
                plot_tree(node.right, next_x + dx + dx, next_y, ax, x, y)
                # Create a plot and display the binary tree
        plt.figure(figsize=(8, 6))
        ax = plt.gca()
        plot_tree(shortTree, 0, 0, ax)
        plt.axis('off')  # Turn off axis labels
        plt.show()
        
    def enterIt(self):
    #initialised variables:
    #first est la formule donnee par l'utilisateur
        first = self.formule.text()
    #final est la meme formule sous notation postfixe et pile une list qui nous aide a calculer
        global final 
        pile =  []
    #proposition is a dictionnary that has variables as keys and later their values(true or false)
        global proposition

    #algorithme de construction studied in class
        i=0
        while(i<len(first)):

    #ignoring spaces
            if(first[i]==' '):
                i = i+1
    
    #if it's proposition we put it directly in final and add ir to proposition dictionnary
            elif first[i]!='¬' and first[i]!='∧' and first[i]!='∨'and first[i]!='→' and first[i]!='↔' and first[i]!='(' and first[i]!=')' : 
                proposition[first[i]] = None
                final.append(first[i])
                i=i+1

    #if it's first priority operator we put it in pile
            elif (first[i]=='('or first[i]=='∨' or first[i]=='∧') :
                while((len(pile)>0) and(first[i]=='∨' or first[i]=='∧')and (pile[-1] == '∨' or pile[-1]== '∧' )):
                    final.append(pile.pop(-1))
                pile.append(first[i])
                i=i+1

    #if it's # or > we check if the last inserted operator in pile has more priorite first if not we insert it in pile
            elif (first[i]=='↔'or first[i]=='→'):
                while((len(pile)>0) and (pile[-1] == '∨' or pile[-1]== '∧' )):
                    final.append(pile.pop(-1))
                pile.append(first[i])
                i=i+1
    # if we have ) we take all operators  from pile to final until we reach ( And if we have ¬ we also put it in first
            elif (first[i]==')'):
                while((len(pile)>0) and (pile[-1]!='(')):
                    final.append(pile.pop(-1))

                pile.pop(-1)  #deleting ( in pile
                if((len(pile)>0) and (pile[-1]=='¬')):
                    final.append(pile.pop(-1))
                i=i+1
    
    # if we find ¬ we check the next thing if it's proposition we put proposition first than ¬ if it's ( we put both ¬ and ( in pile
            elif(first[i]=='¬'):
                if(first[i+1]!='('):
                    final.append(first[i+1])
                    proposition[first[i+1]] = None
                    final.append(first[i])
                else:   
                    pile.append('¬')
                    pile.append('(')
                i=i+2
#once first is done we depile pile in final    
        while(len(pile)>0):
            final.append(pile.pop(-1))

        self.outputlabel.setText(' ∨ '.join(final))
        
#working on tree
        

#creating list of node while putting elements of list final as value of node (right,left are automaticaly giving  None)
        tree=[]
        for i in final:
            tree.append(Node(i))

#loop to make the tree , checking every element of list of nodes(tree)
        i=0
        while(len(tree)>1):    
            a = tree[i].value
    #if it's a proposition we go to the next one
            while(a!='¬' and a!='∧' and a!='∨'and a!='→' and a!='↔' ):
                i=i+1
                a = tree[i].value

    #if node ¬ is not attached to a proposition already we attach it to proposition before
            if(a=='¬' ):
                if(tree[i].right ==None):
                    new = tree.pop(i-1)
                    tree[i-1].right = new
                else :# if it's already attached we ignore it and nest propositions until we find an operator
                    i=i+1
                    a = tree[i].value
                    while(a!='¬' and a!='∧' and a!='∨'and a!='→' and a!='↔' ):
                        i=i+1
                        a = tree[i].value 
     
    #if node is one f these operators we attach it's right and left to elements before and delete them from the list
            elif(a=='∧' or a=='∨'or a=='→' or a=='↔'):
                new1 = tree.pop(i-1)
                new2 = tree.pop(i-2)
                tree[i-2].right = new1
                tree[i-2].left = new2
                i = i-1

#print the tree once it's done
        global treeNode 
        treeNode = tree.pop(0)
        #print("tree for this formula")
        #print(tree[0])

    # put propositions in our table
        column_index = 0
        items = list(proposition.keys())
        self.ValuesT.setRowCount(len(items))
        for i in range(len(items)):  # Assuming you have 5 rows        
            print(items[i])
            item = QtWidgets.QTableWidgetItem(items[i])
            self.ValuesT.setItem(i, column_index, item)
        
        #self.ValuesT.repaint()
        #self.ValuesT.resizeColumnsToContents()
    def calculate(self):
        row=0
        for i in proposition.keys():
            s =  self.ValuesT.item(row, 1).text()
            print(s)
            if s.lower()=='true':
                proposition[i] = True
            else:
                proposition[i] = False 
            row=row+1
        
        global final  
    #create new list that has same elements of final  but the value of propositions instead of proposition itself
        newlist = []
        for i in final:
            if i in proposition.keys():
                newlist.append(proposition[i])
            else:
                newlist.append(i)
        
        

#this loos works the same as the tree loop if we have proposition we ignore it if we have operator we calculate and delete the propositions used in the calculation until we have a final result
        i=0
        while(len(newlist)>1):
    
            while(newlist[i]!='¬' and newlist[i]!='∧' and newlist[i]!='∨'and newlist[i]!='→' and newlist[i]!='↔' ):
                i=i+1

    #if we have ¬ we give it the opposite value of the value of element before and delete the element before
            if(newlist[i]=='¬' ):
                newlist[i]= not newlist[i-1]
                newlist.pop(i-1)
    
            elif(newlist[i]=='∧'):
                newlist[i]=newlist[i-1]and newlist[i-2]
                newlist.pop(i-1)
                newlist.pop(i-2)
                i=i-1
    
            elif(newlist[i]=='∨'):
                newlist[i]=newlist[i-1]or newlist[i-2]
                newlist.pop(i-1)
                newlist.pop(i-2)
                i=i-1
    
            elif(newlist[i]=='→'):
                newlist[i]=  not newlist[i-2] or newlist[i-1]
                newlist.pop(i-1)
                newlist.pop(i-2)
                i=i-1
    
            elif(newlist[i]=='↔'):
                newlist[i]= (not newlist[i-1] or newlist[i-2]) and (not newlist[i-2] or newlist[i-1])
                newlist.pop(i-1)
                newlist.pop(i-2)
                i=i-1
        if(newlist[0]==True):
            self.tfresult.setStyleSheet("color: green;")
        else:
            self.tfresult.setStyleSheet("color: red;")
        self.tfresult.setText(str(newlist[0]))
    
    
        


        

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TRUEorFALSE = QtWidgets.QMainWindow()
    ui = Ui_TRUEorFALSE()
    ui.setupUi(TRUEorFALSE)
    TRUEorFALSE.show()
    sys.exit(app.exec_())
